import asyncio
import sys
import os
from pathlib import Path
from unittest.mock import AsyncMock, patch

# Ensure the backend module is in python path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from backend.application.services.document_assembly_service import DocumentAssemblyService
from backend.application.services.output_export_service import OutputExportService
from backend.application.services.docx_renderer_service import DocxRendererService

def test_phase4_rendering():
    print("🚀 Starting Phase 4 Document Assembly & Rendering Mock Test...\n")

    section_plan = {
        "sections": [
            {"section_id": "s1", "title": "Intro", "execution_order": 1, "generation_strategy": "SUMMARIZE"},
            {"section_id": "s2", "title": "Body", "execution_order": 2, "generation_strategy": "DEEP_DIVE"},
        ]
    }

    generation_results = {
        "s1": {"output_type": "MARKDOWN", "content": "This is the introduction."},
        "s2": {"output_type": "MARKDOWN", "content": "This is the deep dive body."}
    }

    print("[1] Testing DocumentAssemblyService.build_assembled_document()...")
    assembly_svc = DocumentAssemblyService()
    
    assembled = assembly_svc.build_assembled_document(
        workflow_run_id="wkflw_999",
        template_id="tpl_999",
        section_plan=section_plan,
        section_generation_results=generation_results,
        title="Mock Presentation"
    )
    
    assembled_dict = assembled.to_dict()
    assert assembled_dict["total_sections"] == 2
    assert assembled_dict["sections"][0]["title"] == "Intro"
    assert assembled_dict["sections"][0]["content"] == "This is the introduction."
    assert assembled_dict["sections"][1]["title"] == "Body"
    print("   => Assembly Mapping completely valid!")

    print("\n[2] Testing OutputExportService.export_docx()...")
    export_svc = OutputExportService()
    
    # First we prepare the output 
    prepared = export_svc.prepare_docx_export(
        workflow_run_id="wkflw_999",
        assembled_document=assembled_dict
    )
    output_id = prepared["output_id"]
    print(f"   => Prepared Output Entry: {output_id}")

    # Now we execute export
    out_record = export_svc.export_docx(
        output_id=output_id,
        workflow_run_id="wkflw_999",
        assembled_document=assembled_dict
    )
    
    physical_path = out_record["artifact_path"]
    
    assert os.path.exists(physical_path), "DOCX file was not generated by renderer!"
    print(f"   => Successfully generated DOCX at {physical_path}")

    print("\n✅ Phase 4 Mock Test Passed! DOCX is exported flawlessly.\n")


if __name__ == "__main__":
    test_phase4_rendering()
